# Generated by Django 3.0.6 on 2020-05-04 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(-1)])),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
